### ISSUE TITLE
Unsupported number of image dimensions: 2

### ISSUE THREAD

**Issue by inspire22** [lucataco/cog-nsfw_image_detection#1]
Thanks for this!  I'm having trouble with some images, like  https://ap-pics2.gotpoem.com/ap-pics/item/17788/4.jpg?premiumphoto16831247

The same code works with the demo image shown in the playground ( https://replicate.com/lucataco/nsfw_image_detection )

The full log is:
```
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 31, in predict
inputs = self.processor(images=img, return_tensors="pt")
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 549, in __call__
return self.preprocess(images, **kwargs)
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/transformers/models/vit/image_processing_vit.py", line 242, in preprocess
input_data_format = infer_channel_dimension_format(images[0])
File "/root/.pyenv/versions/3.10.13/lib/python3.10/site-packages/transformers/image_utils.py", line 183, in infer_channel_dimension_format
raise ValueError(f"Unsupported number of image dimensions: {image.ndim}")
ValueError: Unsupported number of image dimensions: 2
{"error"=>"Unsupported number of image dimensions: 2"}
```

**Comment by lucataco** [comment]
Bad user input image, this model assumes RGB images whereas this image only has 1 ColorComponent

**Comment by inspire22** [comment]
Thanks! I need to do NSFW detection on user-uploaded images so who knows what format they'll be using.  Any suggestions how to use convert or tweak something to allow it to work with these differently composed images?

**Comment by inspire22** [comment]
Just checking up on this, a NSFW detector that only works on 30% of images is pretty useless...
